-- Patch notes data structure - update this for each release
PATCH_NOTES = { {
  version = '1.0.0',
  date = '2026-01-28',
  expansion = 'TBC',
  notes = {
    'TODO:',
    '• Make Max HP a "best ever hp" stat.',
    '• HEROIC dungeon deaths',
    '• Per dungeon completion stats (final boss kill)',   
    '• Per heroic dungeon completion stats (final boss kill)',   
    '• Per raid completion stats (final boss kill)',   
    '• Wipes per boss per dungeon/raid',   
    '• Dungeon and Raid statistics',   
    '',
    'Initial release of Ultra Statistics.',
    '',
    'FEATURES: ',
    '• Port over all existing functionality from Ultra.',
    '• Import button to import stats from Ultra.',
    '• Added Raid and Dungeon Boss IDs for TBC.',
    '',
    'NEW STATISTICS:',
    '• Added statistics for:',
    '  - Deaths',
    '  - Deaths (Open World)',
    '  - Deaths (Battleground)',
    '  - Deaths (Dungeon)',
    '  - Deaths (Raid)',
    '  - Deaths (Arena)',
    '  - Max Health',
    '  - Max Resource',
    '  - Blocks',
    '  - Dodges',
    '  - Parries',
    '  - Resists',
  },
} }
