-- Patch notes data structure - update this for each release
PATCH_NOTES = { {
  version = '1.0.0',
  date = '2026-01-28',
  expansion = 'TBC',
  notes = {
    'TODO:',
    '• HEROIC dungeon deaths',
    '',
    'Initial release of Ultra Statistics.',
    '',
    'FEATURES: ',
    '• Port over all existing functionality from Ultra.',
    '• Import button to import stats from Ultra.',
    '• Added Raid and Dungeon Boss IDs for TBC.',
    '',
    'NEW STATISTICS:',
    '• Added statistics for:',
    '  - Deaths',
    '  - Deaths (Open World)',
    '  - Deaths (Battleground)',
    '  - Deaths (Dungeon)',
    '  - Deaths (Raid)',
    '  - Deaths (Arena)',
    '  - Highest Health',
    '  - Highest Resource',
    '  - Blocks',
    '  - Dodges',
    '  - Parries',
    '  - Resists',
  },
} }
